[package]
name = "chat_client"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = { version = "1.44.0", features = ["full"]}
crossterm = "0.29.0"
ratatui = {version = "0.29.0", features = ["crossterm"]}